Adding endpoint to verify email, adding email verification functionality
ndv6/tsaving pull request #11
Opened 2020-07-22 07:20 UTC by polipopoliko

2020-07-22 07:57 UTC, yulyulyharuka requested changes

2020-07-22 07:57 UTC, yulyulyharuka commented on api/email/verify_email_token.go
> +		if err != nil {
return supaya kalo error ga lanjut

2020-07-22 07:57 UTC, yulyulyharuka commented on api/email/verify_email_token.go
> +		fmt.Fprintf(w, "Email %v has been succesfully verified at %v\n", et.Email, time.Now())
return json {
"email" : "email@example.com",
"status": "verified"
}

2020-07-23 02:26 UTC, vicimilenia requested changes

2020-07-23 02:26 UTC, vicimilenia commented on api/email/verify_email_token.go
> +		}
this part will never run because you already return in line 39

2020-07-23 10:56 UTC, david1312 approved these changes
good to go

2020-07-23 17:48 UTC, yulyulyharuka approved these changes

2020-07-24 00:06 UTC, merged