Feature/admin dashboard
ndv6/tsaving pull request #124
Opened 2020-08-09 15:52 UTC by polipopoliko

2020-08-09 16:57 UTC, david1312 approved these changes

2020-08-10 02:20 UTC, vicimilenia requested changes

2020-08-10 02:20 UTC, vicimilenia commented on database/database_admin.go
> +	}
There's no need for this as we're going to run `return` anyways

2020-08-10 02:36 UTC, sekarminati approved these changes

2020-08-10 02:46 UTC, vicimilenia approved these changes

2020-08-10 02:50 UTC, merged