Adding Description template for log transaction
ndv6/tsaving pull request #20
Opened 2020-07-22 15:37 UTC by polipopoliko

2020-07-22 16:45 UTC, yulyulyharuka requested changes

2020-07-22 16:45 UTC, yulyulyharuka commented on api/email/verify_email_token.go
>  	}
add return at the end of the http.HandlerFunc

2020-07-22 23:12 UTC, david1312 approved these changes
ok

2020-07-23 03:29 UTC, vicimilenia requested changes

2020-07-23 03:29 UTC, vicimilenia commented on api/email/verify_email_token.go
> +		}
remove this, as the previous err != nil already return the function

2020-07-23 03:29 UTC, vicimilenia commented on api/vac/virtual_accounts.go
> +			helpers.HTTPError(w, http.StatusBadRequest, "Fail to revert balance to main account")
```suggestion
			helpers.HTTPError(w, http.StatusBadRequest, "Fail to delete vac(?)")
```

2020-07-23 03:29 UTC, vicimilenia commented on database/virtual_accounts.go
> +		_, err = db.Exec("UPDATE ACCOUNTS SET account_balance=$1 WHERE account_id=$2;", acc.AccountBalance+va.VaBalance, acc.AccountId)
```suggestion
		_, err = db.Exec("UPDATE accounts SET account_balance=$1 WHERE account_id=$2;", acc.AccountBalance+va.VaBalance, acc.AccountId)
```

2020-07-23 03:29 UTC, vicimilenia commented on database/virtual_accounts.go
> +	_, err = db.Exec("DELETE FROM VIRTUAL_ACCOUNTS WHERE va_id=$1;", vId)
```suggestion
	_, err = db.Exec("DELETE FROM virtual_accounts WHERE va_id=$1;", vId)
```

2020-07-23 03:29 UTC, vicimilenia commented on database/virtual_accounts.go
> +	err = db.QueryRow("SELECT account_id, account_num, account_balance, created_at FROM ACCOUNTS WHERE account_num=$1", accountNum).Scan(&acc.AccountId, &acc.AccountNum, &acc.AccountBalance, &acc.Create
```suggestion
	err = db.QueryRow("SELECT account_id, account_num, account_balance, created_at FROM accounts WHERE account_num=$1", accountNum).Scan(&acc.AccountId, &acc.AccountNum, &acc.AccountBalance, &acc.CreatedAt)
```

2020-07-23 03:29 UTC, vicimilenia commented on database/virtual_accounts.go
> +	err = db.QueryRow("SELECT cust_id, account_num, email FROM CUSTOMERS WHERE cust_id=$1;", id).Scan(&cust.CustId, &cust.AccountNum, &cust.CustEmail)
```suggestion
	err = db.QueryRow("SELECT cust_id, account_num, email FROM customers WHERE cust_id=$1;", id).Scan(&cust.CustId, &cust.AccountNum, &cust.CustEmail)
```

2020-07-23 03:29 UTC, vicimilenia commented on database/virtual_accounts.go
> +	err = db.QueryRow("SELECT va_id, va_num, account_num, va_balance FROM VIRTUAL_ACCOUNTS WHERE account_num=$1", accountNum).Scan(&va.VaId, &va.VaNum, &va.AccountNum, &va.VaBalance)
```suggestion
	err = db.QueryRow("SELECT va_id, va_num, account_num, va_balance FROM virtual_accounts WHERE account_num=$1", accountNum).Scan(&va.VaId, &va.VaNum, &va.AccountNum, &va.VaBalance)
```

2020-07-23 09:28 UTC, david1312 approved these changes
good to go

2020-07-23 17:52 UTC, yulyulyharuka commented on database/database_virtual_accounts.go
> +	fmt.Println(err)
i think you can use log.Println() instead of fmt.Println() to print the error

2020-07-23 17:52 UTC, yulyulyharuka commented on database/database_virtual_accounts.go
> +	fmt.Println(err)
or you can delete it i think and throw the error in the handler

2020-07-23 17:52 UTC, yulyulyharuka commented on database/database_virtual_accounts.go
> +		fmt.Println(err)
the same problem here

2020-07-24 01:50 UTC, yulyulyharuka approved these changes
lgtm

2020-07-24 02:06 UTC, merged