Feature/register
ndv6/tsaving pull request #34
Opened 2020-07-23 08:47 UTC by caesargusti

models/accounts
api/customers/customer

2020-07-23 08:53 UTC, sekarminati requested changes

2020-07-23 08:53 UTC, sekarminati commented on helpers/helpers.go
>  	return cfg, err
Please change this to "return"

2020-07-23 08:53 UTC, sekarminati commented on models/accounts.go
> +		return err
Please change this to "return"

2020-07-23 15:26 UTC, david1312 approved these changes
good to go

2020-07-23 17:59 UTC, yulyulyharuka requested changes

2020-07-23 17:59 UTC, yulyulyharuka commented on api/customers/customers.go
> +var emailRegex = regexp.MustCompile("^[a-zA-Z0-9.!#$%&'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$")
you can move emailRegex into inside isEmailValid function because u dont need this globally

2020-07-23 18:02 UTC, yulyulyharuka requested changes

2020-07-23 18:02 UTC, yulyulyharuka commented on api/customers/customers.go
> +	log.Println(string(body))
check if the body is error or not, if the api returning error then handle it

2020-07-24 02:11 UTC, vicimilenia approved these changes

2020-07-24 03:03 UTC, merged