Adding function listenAndServe to port 8000
ndv6/tsaving pull request #5
Opened 2020-07-21 11:29 UTC by polipopoliko

2020-07-21 14:20 UTC, david1312 approved these changes

2020-07-21 14:26 UTC, vicimilenia requested changes

2020-07-21 14:26 UTC, vicimilenia commented on main.go
> +	"github.com/polipopoliko/tsaving/tsaving/database"
change /polipopoliko/ to /ndv6/ in line 8 and  9
```suggestion
	"github.com/ndv6/tsaving/tsaving/database"
```

2020-07-21 14:26 UTC, vicimilenia commented on go.mod
> +module github.com/polipopoliko/tsaving/tsaving
```suggestion
module github.com/ndv6/tsaving
```

2020-07-21 14:26 UTC, vicimilenia commented on go.mod
> +// change the module path to your directory
No need for this comment, as ideally all repository cloned to personal laptops follows the format github.com/ndv6/tsaving

2020-07-21 14:26 UTC, vicimilenia commented on api/router.go
> +func HomeHandler(w http.ResponseWriter, r *http.Request) {
Move this to another file named home/homepage/homehandler.go under the api folder

2020-07-21 14:26 UTC, vicimilenia commented on api/router.go
> +func NotFoundHandler(w http.ResponseWriter, r *http.Request) {
Move this to another file named not_found/not_found_page/not_found_handler.go under the api folder

2020-07-21 22:49 UTC, celynolivia approved these changes

2020-07-22 01:53 UTC, vicimilenia requested changes

2020-07-22 01:53 UTC, vicimilenia commented on api/router.go
> +	"github.com/polipopoliko/ndv6/tsaving/api/not_found/not_found_page"
```suggestion
	"github.com/ndv6/tsaving/api/home/homepage"
	"github.com/ndv6/tsaving/api/not_found/not_found_page"
```

2020-07-22 01:53 UTC, vicimilenia commented on go.mod
> +module github.com/polipopoliko/ndv6/tsaving
```suggestion
module github.com/ndv6/tsaving
```

2020-07-22 01:53 UTC, vicimilenia commented on main.go
> +	"github.com/polipopoliko/ndv6/tsaving/database"
```suggestion
	"github.com/ndv6/tsaving/api"
	"github.com/ndv6/tsaving/database"
```

2020-07-22 02:27 UTC, vicimilenia approved these changes

2020-07-22 02:27 UTC, merged