Function Cek Rekening
ndv6/tsaving pull request #9
Opened 2020-07-22 03:57 UTC by jocelyntjahyadi

Fungsi untuk mengecek apakah input rekening ada di database atau tidak.

CheckRekeningVA -> untuk mengecek rekening VirtualAccount

CheckRekening -> untuk mengecek rekening utama

Terimakasii

2020-07-22 05:04 UTC, vicimilenia requested changes

2020-07-22 05:04 UTC, vicimilenia commented on tokens/jwt.go
> +	helper "github.com/jocelyntjahyadi/tsaving/helpers"
```suggestion
	helper "github.com/ndv6/tsaving/helpers"
```

2020-07-22 05:04 UTC, vicimilenia commented on api/virtual_accounts/virtual_accounts.go
> +// }
please remove/don't commit comment if not needed

2020-07-22 05:04 UTC, vicimilenia commented on tokens/tokens.go
> +	if t.Expired.Before(time.Now()) { //kalau sebelum saat ini, token expired
```suggestion
	if t.Expired.Before(time.Now()) && t.Expired.Equal(time.Now())  { //kalau sebelum saat ini, token expired
```
so that if the token expired exactly right now, it will still be invalid

2020-07-22 05:04 UTC, vicimilenia commented on models/virtual_accounts.go
> +//
remove unused comment

2020-07-22 05:04 UTC, vicimilenia commented on models/virtual_accounts.go
> +func (va *VirtualAccounts) UpdateVacBalance(db *sql.DB, saldoInput float64, RekVac string) error {
change variable names to english as per yesterday's agreements

2020-07-22 05:04 UTC, vicimilenia commented on models/virtual_accounts.go
> +	}
No need for this, as we directly return error after this line

2020-07-22 05:04 UTC, vicimilenia commented on models/virtual_accounts.go
> +	return NoRek, nil
```suggestion
	return
```

2020-07-22 05:04 UTC, vicimilenia commented on tokens/jwt.go
> +	//
remove comment in this line

2020-07-22 05:04 UTC, vicimilenia commented on tokens/jwt.go
> +func (j *JWT) GetToken(r *http.Request) Token {
```suggestion
func (j *JWT) GetToken(r *http.Request) (token Token, err Error) {
```

2020-07-22 05:04 UTC, vicimilenia commented on tokens/jwt.go
> +	token, ok := r.Context().Value("token").(Token) // r.Context() -> variable per request
```suggestion
	token, err = r.Context().Value("token").(Token) // r.Context() -> variable per request
```

2020-07-22 05:04 UTC, vicimilenia commented on tokens/jwt.go
> +	return token
```suggestion
	return
```

2020-07-22 05:04 UTC, vicimilenia commented on main.go
> +	// jwt := token.New([]byte(cfg.JWTSecret))
if needed, please uncomment. If not, please remove/don't commit

2020-07-22 05:04 UTC, vicimilenia commented on helpers/helpers.go
> +	NoRek := 0
please change variable names to english as per yesterday's agreement

2020-07-22 05:04 UTC, vicimilenia commented on helpers/helpers.go
> +func CheckRekening(db *sql.DB, Rek string) error {
```suggestion
func CheckRekening(db *sql.DB, Rek string) (err error) {
```

2020-07-22 05:04 UTC, vicimilenia commented on helpers/helpers.go
> +	return nil
```suggestion

	return
```

2020-07-22 05:04 UTC, vicimilenia commented on helpers/helpers.go
> +	VirtualRek := 0
please change variable names to english as per yesterday's agreement

2020-07-22 05:04 UTC, vicimilenia commented on helpers/helpers.go
> +	// token := ch.jwt.GetToken(r)
if needed, please uncomment. If not, please remove/don't commit

2020-07-22 05:04 UTC, vicimilenia commented on configs/configs.json
> +
please don't commit as per yesterday's agreement

2020-07-22 05:04 UTC, vicimilenia commented on api/virtual_accounts/virtual_accounts.go
> +		// helper.HTTPError(w, http.StatusBadRequest, "error updating account balance")
if needed, please uncomment. If not, please remove/don't commit

2020-07-22 05:04 UTC, vicimilenia commented on api/virtual_accounts/virtual_accounts.go
> +		// helper.HTTPError(w, http.StatusBadRequest, "error updating virtual account balance")
if needed, please uncomment. If not, please remove/don't commit

2020-07-22 05:04 UTC, vicimilenia commented on api/virtual_accounts/virtual_accounts.go
> +	NoRek, _ := ViA.GetRekeningByVA(va.db, VirAc.RekVac)
please change all variable names to english

2020-07-22 05:04 UTC, vicimilenia commented on api/router.go
> +	// VAC trsnsactions API endpoints
```suggestion
	// VAC transactions API endpoints
```

2020-07-22 05:04 UTC, vicimilenia commented on tokens/jwt.go
> +		// fmt.Fprintf(w, "Login as %v\n", claims.User)
if needed, please uncomment. If not, please remove/don't commit

2020-07-22 05:04 UTC, vicimilenia commented on tokens/jwt.go
> +		//
if needed, please uncomment. If not, please remove/don't commit

2020-07-22 05:11 UTC, vicimilenia requested changes

2020-07-22 05:11 UTC, vicimilenia commented on api/virtual_accounts/virtual_accounts.go
> +	RekVac     string  `json:"rekening_vac"`
please change all naming to english

2020-07-22 05:11 UTC, vicimilenia commented on api/virtual_accounts/virtual_accounts.go
> +		helper.HTTPError(w, http.StatusBadRequest, "unable to request body")
```suggestion
		helper.HTTPError(w, http.StatusBadRequest, "unable to <read? parse?> request body")
```

2020-07-22 06:25 UTC, vicimilenia requested changes

2020-07-22 06:25 UTC, vicimilenia commented on tokens/tokens.go
> +func (t *Token) Valid() error {
```suggestion
func (t *Token) Valid() (err error) {
```

2020-07-22 06:25 UTC, vicimilenia commented on tokens/tokens.go
> +	return nil
```suggestion
	return
```

2020-07-22 06:25 UTC, vicimilenia commented on tokens/tokens.go
> +		return errors.New("token expired")
```suggestion
		err = errors.New("token expired")
```

2020-07-23 05:01 UTC, polipopoliko requested changes

2020-07-23 05:01 UTC, polipopoliko commented on api/virtual_accounts/virtual_accounts.go
> +type InputVac struct {
Change it to InputVa

2020-07-23 05:01 UTC, polipopoliko commented on api/virtual_accounts/virtual_accounts.go
> +	VacNumber     string `json:"va_num"`
change it to VaNum

2020-07-23 05:01 UTC, polipopoliko commented on api/virtual_accounts/virtual_accounts.go
> +		// fmt.Fprint(w, err)
remove comment if not needed

2020-07-23 05:01 UTC, polipopoliko commented on api/virtual_accounts/virtual_accounts.go
> +	// fmt.Fprint(w, err)
remove comment if not needed

2020-07-23 05:01 UTC, polipopoliko commented on api/virtual_accounts/virtual_accounts.go
> +
After the update is completed please log the transaction to database

2020-07-23 05:01 UTC, polipopoliko commented on test/virtual_accounts/virtual_accounts.go
> +}
No need to be push

2020-07-23 10:53 UTC, merged